import { useMemo, useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { useTranslation } from "react-i18next";
import { jsPDF } from "jspdf";
import { api } from "@/services/api";
import { usePreferences } from "@/stores/usePreferences";
import type { RankingRequest } from "@/types/api";
import type { ApiRankingResponse, IndicatorContribution, RankingItem } from "@/types/ranking";

const baseUrl=import.meta.env.VITE_API_BASE_URL??"/api/v1";
async function requestRanking(payload:RankingRequest):Promise<ApiRankingResponse>{const response=await fetch(`${baseUrl}/rankings`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});if(!response.ok)throw new Error("errors.network");return response.json() as Promise<ApiRankingResponse>}

function ResultCard({item,onEvidence}:{item:RankingItem;onEvidence:(item:IndicatorContribution)=>void}){const {t}=useTranslation();const strongest=useMemo(()=>item.indicators.filter((entry)=>entry.score!==null).sort((a,b)=>(b.score??0)-(a.score??0)).slice(0,3),[item.indicators]);return <article className="result-card"><header><div><p className="eyebrow">{item.location.locationType}</p><h2>{item.location.name}</h2></div><div className="score-disc"><strong>{item.destinationScore===null?"—":Math.round(item.destinationScore)}</strong><span>/100</span></div></header><div className="quality-trio"><div><span>{t("compare.score")}</span><strong>{item.destinationScore===null?"—":Math.round(item.destinationScore)}</strong></div><div><span>{t("compare.coverage")}</span><strong>{Math.round(item.dataCoverage)}%</strong></div><div><span>{t("compare.confidence")}</span><strong>{t(`quality.${item.methodologicalConfidence}`)}</strong></div></div><p className={`constraint ${item.constraintsMet?"pass":"fail"}`}>{t(item.constraintsMet?"compare.constraintsMet":"compare.constraintsFailed")}</p>{strongest.length>0&&<div className="contributions"><h3>{t("compare.strengths")}</h3>{strongest.map((indicator)=><button key={indicator.indicatorCode} onClick={()=>onEvidence(indicator)}><span>{t(`categories.${indicator.categoryCode}`)} <code>{indicator.indicatorCode}</code></span><strong>{Math.round(indicator.score??0)}</strong></button>)}</div>}<p className="official-note">{t("compare.officialOnly")}</p></article>}

function EvidenceDialog({item,onClose}:{item:IndicatorContribution;onClose:()=>void}){const {t}=useTranslation();const value=(key:string,data:string|null)=>data&&<div><dt>{t(key)}</dt><dd>{data}</dd></div>;return <div className="dialog-backdrop" role="presentation" onMouseDown={onClose}><section className="evidence-dialog" role="dialog" aria-modal="true" onMouseDown={(event)=>event.stopPropagation()}><button className="dialog-close" onClick={onClose}>{t("actions.close")}</button><p className="eyebrow">{item.indicatorCode}</p><h2>{t(`categories.${item.categoryCode}`)}</h2><div className="evidence-score"><strong>{item.score===null?"—":Math.round(item.score)}</strong><span>{item.rawValue} {item.unit}</span></div>{item.observation.geographicLevel!=="city"&&<p className="warning-inline">{t("compare.nationalWarning")}</p>}<dl>{value("quality.producer",item.observation.organization)}{value("quality.reference",`${item.observation.periodStart} — ${item.observation.periodEnd}`)}{value("quality.published",item.observation.publishedAt)}{value("quality.retrieved",item.observation.retrievedAt)}{value("quality.unit",item.unit)}{value("quality.method",item.observation.methodologyVersion)}{value("quality.geography",item.observation.geographicLevel)}{value("quality.status",item.observation.qualityStatus)}{value("quality.transformations",item.observation.transformations.join(" · "))}</dl><a className="button secondary" href={item.observation.sourceUrl} target="_blank" rel="noreferrer">{t("quality.source")}</a></section></div>}

function downloadExcel(result:ApiRankingResponse){const escape=(value:string)=>value.replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");const rows=[["Destination","Score","Coverage","Confidence","Constraints met"],...result.results.map((item)=>[item.location.name,String(item.destinationScore??""),String(item.dataCoverage),item.methodologicalConfidence,String(item.constraintsMet)])];const xml=`<?xml version="1.0"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><Worksheet ss:Name="Comparison"><Table>${rows.map((row)=>`<Row>${row.map((value)=>`<Cell><Data ss:Type="String">${escape(value)}</Data></Cell>`).join("")}</Row>`).join("")}</Table></Worksheet></Workbook>`;const url=URL.createObjectURL(new Blob([xml],{type:"application/vnd.ms-excel"}));const link=document.createElement("a");link.href=url;link.download="norevia-comparison.xls";link.click();URL.revokeObjectURL(url)}

export function ComparePage(){
  const {t}=useTranslation();const profile=usePreferences((state)=>state.profile);const weights=usePreferences((state)=>state.weights);const constraints=usePreferences((state)=>state.constraints);const selected=usePreferences((state)=>state.selectedLocations);const setSelected=usePreferences((state)=>state.setSelectedLocations);const save=usePreferences((state)=>state.saveComparison);const [evidence,setEvidence]=useState<IndicatorContribution|null>(null);
  const locations=useQuery({queryKey:["locations","DE","city"],queryFn:api.locations});const ranking=useMutation({mutationFn:requestRanking,onSuccess:(result)=>save(result as never)});
  const toggle=(slug:string)=>setSelected(selected.includes(slug)?selected.filter((item)=>item!==slug):selected.length<4?[...selected,slug]:selected);const compare=()=>ranking.mutate({locationType:"city",countries:["DE"],locationSlugs:selected,household:{adults:profile.adults,children:profile.childrenAges.length},weights,constraints});
  const exportPdf=()=>{if(!ranking.data)return;const document=new jsPDF();document.setFontSize(20);document.text("Norevia",20,20);ranking.data.results.forEach((item,index)=>document.text(`${index+1}. ${item.location.name} — ${item.destinationScore===null?"—":Math.round(item.destinationScore)}/100 · ${Math.round(item.dataCoverage)}%`,20,38+index*12));document.save("norevia-comparison.pdf")};
  return <section className="page"><p className="eyebrow">03 · {t("nav.compare")}</p><h1>{t("compare.title")}</h1><p className="page-intro">{t("compare.intro")}</p><div className="location-picker"><h2>{t("compare.select")}</h2>{locations.isLoading&&<div className="skeleton-grid"><i/><i/><i/><i/></div>}{locations.data?.map((location)=><label key={location.slug} className={selected.includes(location.slug)?"location-chip selected":"location-chip"}><input type="checkbox" checked={selected.includes(location.slug)} onChange={()=>toggle(location.slug)} disabled={!selected.includes(location.slug)&&selected.length>=4}/><span>{location.name}</span></label>)}<button className="button primary compare-button" disabled={!selected.length||ranking.isPending} onClick={compare}>{t("actions.compare")}</button></div>{ranking.isError&&<div className="error-panel"><p>{t("errors.network")}</p><button onClick={compare}>{t("actions.retry")}</button></div>}{ranking.data&&<><div className="results-toolbar"><span>{ranking.data.results.length} / {selected.length}</span><button onClick={exportPdf}>{t("actions.exportPdf")}</button><button onClick={()=>downloadExcel(ranking.data!)}>{t("actions.exportExcel")}</button></div>{ranking.data.results.length===0?<div className="empty-state"><span>∅</span><h2>{t("compare.empty")}</h2><p>{t("compare.emptyHelp")}</p></div>:<div className="results-grid">{ranking.data.results.map((item)=><ResultCard key={item.location.id} item={item} onEvidence={setEvidence}/>)}</div>}</>}{evidence&&<EvidenceDialog item={evidence} onClose={()=>setEvidence(null)}/>}</section>;
}
