import { useMemo, useState } from "react";
import { useTranslation } from "react-i18next";
import { useNavigate } from "react-router-dom";
import { categories, usePreferences, type Category, type RankingRequestConstraint } from "@/stores/usePreferences";

type FilterState={rent:string;unemployment:string;commute:string;airport:string};
export function PrioritiesPage(){
  const {t}=useTranslation();const navigate=useNavigate();const {weights,setWeight,setConstraints}=usePreferences();const [filters,setFilters]=useState<FilterState>({rent:"",unemployment:"",commute:"",airport:""});
  const total=useMemo(()=>Object.values(weights).reduce((sum,value)=>sum+value,0),[weights]);const valid=Math.abs(total-100)<0.01;
  const update=(key:keyof FilterState,value:string)=>setFilters((current)=>({...current,[key]:value}));
  const submit=()=>{const definitions:[keyof FilterState,string,"lte"][]=[["rent","median_cold_rent","lte"],["unemployment","unemployment_rate","lte"],["commute","average_commute_time","lte"],["airport","airport_access_time","lte"]];const constraints:RankingRequestConstraint[]=definitions.flatMap(([key,indicatorCode,operator])=>filters[key]?[{indicatorCode,operator,value:Number(filters[key]),required:true}]:[]);setConstraints(constraints);navigate("/compare")};
  return <section className="page"><p className="eyebrow">02 · {t("nav.priorities")}</p><div className="page-heading"><div><h1>{t("priorities.title")}</h1><p className="page-intro">{t("priorities.intro")}</p></div><div className={`total-ring ${valid?"valid":"invalid"}`}><strong>{total}</strong><span>{t("priorities.total")}</span></div></div><div className="weight-list">{categories.map((category)=><label className="weight-row" key={category}><span>{t(`categories.${category}`)}</span><input type="range" min="0" max="40" step="1" value={weights[category]} onChange={(event)=>setWeight(category as Category,Number(event.target.value))}/><output>{weights[category]}</output></label>)}</div><section className="filter-panel"><h2>{t("priorities.filters")}</h2><div className="form-grid"><label>{t("priorities.maxRent")}<input type="number" min="0" value={filters.rent} onChange={(event)=>update("rent",event.target.value)}/></label><label>{t("priorities.maxUnemployment")}<input type="number" min="0" max="100" value={filters.unemployment} onChange={(event)=>update("unemployment",event.target.value)}/></label><label>{t("priorities.maxCommute")}<input type="number" min="0" value={filters.commute} onChange={(event)=>update("commute",event.target.value)}/></label><label>{t("priorities.airport")}<input type="number" min="0" value={filters.airport} onChange={(event)=>update("airport",event.target.value)}/></label></div></section><div className="sticky-action"><p className={valid?"success-text":"error-text"}>{t(valid?"priorities.valid":"priorities.invalid")}</p><button className="button primary" disabled={!valid} onClick={submit}>{t("actions.compare")}</button></div></section>;
}
