import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";
import { useTranslation } from "react-i18next";
import { useNavigate } from "react-router-dom";
import { z } from "zod";
import { usePreferences } from "@/stores/usePreferences";
import type { ProfileState } from "@/types/api";

const schema=z.object({name:z.string().min(1),adults:z.coerce.number().int().min(1).max(12),childrenAgesText:z.string(),occupation:z.string(),sector:z.string(),disposableIncome:z.coerce.number().nonnegative().nullable(),languagesText:z.string(),mobility:z.enum(["car","transit","both"]),tenure:z.enum(["rent","buy"]),entrepreneurialProject:z.boolean(),climatePreference:z.enum(["cool","temperate","warm"])});
type FormValues=z.infer<typeof schema>;

export function ProfilePage(){
  const {t}=useTranslation();const navigate=useNavigate();const profile=usePreferences((state)=>state.profile);const setProfile=usePreferences((state)=>state.setProfile);
  const {register,handleSubmit,formState:{errors}}=useForm<FormValues>({resolver:zodResolver(schema),defaultValues:{...profile,childrenAgesText:profile.childrenAges.join(", "),languagesText:profile.languages.join(", ")}});
  const submit=(value:FormValues)=>{const next:ProfileState={name:value.name,adults:value.adults,occupation:value.occupation,sector:value.sector,disposableIncome:value.disposableIncome,languages:value.languagesText.split(",").map((item)=>item.trim()).filter(Boolean),childrenAges:value.childrenAgesText.split(",").map(Number).filter((age)=>Number.isInteger(age)&&age>=0),mobility:value.mobility,tenure:value.tenure,entrepreneurialProject:value.entrepreneurialProject,climatePreference:value.climatePreference};setProfile(next);navigate("/priorities")};
  return <section className="page narrow"><p className="eyebrow">01 · {t("nav.profile")}</p><h1>{t("profile.title")}</h1><p className="page-intro">{t("profile.intro")}</p><form className="form-grid" onSubmit={handleSubmit(submit)}><label className="wide">{t("profile.name")}<input {...register("name")} aria-invalid={!!errors.name}/></label><label>{t("profile.adults")}<input type="number" {...register("adults")}/></label><label>{t("profile.childrenAges")}<input {...register("childrenAgesText")} placeholder="4, 8"/></label><label>{t("profile.occupation")}<input {...register("occupation")}/></label><label>{t("profile.sector")}<input {...register("sector")}/></label><label>{t("profile.income")}<input type="number" {...register("disposableIncome")}/></label><label>{t("profile.languages")}<input {...register("languagesText")} placeholder="Deutsch, English"/></label><fieldset><legend>{t("profile.mobility")}</legend>{(["car","transit","both"] as const).map((value)=><label className="choice" key={value}><input type="radio" value={value} {...register("mobility")}/>{t(`profile.${value}`)}</label>)}</fieldset><fieldset><legend>{t("profile.tenure")}</legend>{(["rent","buy"] as const).map((value)=><label className="choice" key={value}><input type="radio" value={value} {...register("tenure")}/>{t(`profile.${value}`)}</label>)}</fieldset><fieldset><legend>{t("profile.climate")}</legend>{(["cool","temperate","warm"] as const).map((value)=><label className="choice" key={value}><input type="radio" value={value} {...register("climatePreference")}/>{t(`profile.${value}`)}</label>)}</fieldset><label className="check"><input type="checkbox" {...register("entrepreneurialProject")}/>{t("profile.entrepreneur")}</label><div className="form-actions wide"><button className="button primary" type="submit">{t("actions.continue")}</button></div></form></section>;
}
